### ISSUE TITLE
README doesn't render properly in Pypi

### ISSUE THREAD

**Issue by scls19fr** [pypa/readme#28]
Hello,

I'm trying to publish a Python package
https://pypi.python.org/pypi?:action=display&name=pandas_confusion&version=0.0.1

Code is available here
https://github.com/scls19fr/pandas_confusion

but README doesn't seems to be properly parsed by Pypi

Any idea ?

Kind regards

see https://github.com/msabramo/setuptools-markdown/issues/5

**Comment by mgedmin** [comment]
My favourite debugging technique for this is
```
$ pip install restview
$ git clone https://github.com/scls19fr/pandas_confusion
$ cd pandas_confusion
$ restview --long-description
```

I'm seeing
> <string>:62: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.

where line 62 of the generated ReStructuredText is
![buggy ReST](https://cloud.githubusercontent.com/assets/159967/8002819/7b55014e-0b7a-11e5-8cff-99862db19b2e.png)

(Screenshotted because GitHub doesn't let you have a line consisting solely of `~~~` inside a code block without messing everything up.)

You can get the generated ReStructuredText by doing
```
$ python setup.py --long-description > generated.rst
```

I suggest you file a [setuptools-markdown](https://github.com/msabramo/setuptools-markdown) bug, because it's generating invalid ReStructuredText.  Or maybe a pandoc bug?  (Where does pandoc hide its bug tracker?)

**Comment by scls19fr** [comment]
This problem is solved.

It was a pandoc issue with my old version of pandoc

see https://github.com/jgm/pandoc/issues/2179

Thanks
